apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/config
  prune: true
  postBuild:
    substitute:
      KEYVAULT_URL: "https://platform01runnerseusdevk.vault.azure.net"
      AZURE_TENANT_ID: "fa7492f3-e949-4bd8-9963-e88b76996320"
      MANAGED_IDENTITY_CLIENT_ID: "b8089c8c-2a34-48e5-a614-7a4b262645d2"
